### Create artist
< {%
  const signature = crypto.hmac.sha256()
    .withTextSecret(request.environment.get("secret"))
    .updateWithText(request.body.tryGetSubstituted())
    .digest().toBase64();
  request.variables.set("signature", signature)
%}
POST https://chinook.loca.lt/api/external/v1/artists
Content-Type: application/json
x-chinook-hmac-sha256: {{signature}}

{
  "artistName": "The Boss 10"
}
