### Create artist
< {%
  const signature = crypto.hmac.sha256()
    .withTextSecret(request.environment.get("secret"))
    .updateWithText(request.body.tryGetSubstituted())
    .digest().toBase64();
  request.variables.set("signature", signature)
%}
POST https://chinook.loca.lt/api/external/v1/artists
Content-Type: application/json
x-chinook-hmac-sha256: {{signature}}

{
  "artistName": "The Boss 11"
}

### Query
POST http://localhost:4000/api/external/v1/search
Content-Type: application/json

{
  "query": "dark theme metal"
}

###{
###  "query": "This mission is too important for me to allow you to jeopardize it."
###}
